version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "#Caio159357"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  app:
    build: .
    environment:
      DbServer: "ms-sql-server"
      DbName: "UserDockerDb"
    ports: 
      - "8080:80"
    