version: "3.7"

services:

    db:
        image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
        container_name: db
        restart: "always"
        ports: 
         - "1433:1433"
        environment:
         ACCEPT_EULA: "Y"
         SA_PASSWORD: "#Caio159357"
         MSSQL_PID: "Developer"

        networks:
         - network-app
        
    
    app:
        image: crud/caio
        build:
            context: .
        container_name: app_container
        ports:
         - "5000:80"
        networks:
         - network-app
        depends_on:
         - db
        
networks:
    network-app:
        driver: bridge
